name: dailywork
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63334
title: dailywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8dbec'
    - '#17739a'
    - '#2f94c0'
    - '#cdc0b8'
    - '#96837c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
