name: dailyworks
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5218932505231351
title: dailywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffafa'
    - '#0e0f09'
    - '#b45225'
    - '#ac8a80'
    - '#325159'
  brandStrength: 0.45875472761690617
  lightness: 0.7058209397364408
  saturation: 0.40402777842245996
  rhythmicContrast: 0.8947615481447428
purpose: []
